### ISSUE TITLE
Moderation improvements

### ISSUE THREAD

**Issue by ClearlyClaire** [mastodon/mastodon#18242]
### Pitch

- [x] flexible user roles with custom sets of permissions instead of admin/mod roles
- [x] admin APIs for managing federation
- [x] webhook system for admin API events (e.g. signups)
- [x] notifications about new sign-ups and new reports in the Web UI
  - [x] new sign-ups
  - [x] new reports
- [ ] some moderation actions directly from the Web UI

### Motivation

Part of our NLnet proposal

**Comment by connyduck** [comment]
Please also expose the role of an account via the RestApi, so that client apps can show "this is an admin of your instance" indicators on profiles.
